CREATE TABLE Article
(
 ArticleId INT IDENTITY(1,1) PRIMARY KEY,
 AuthorId INT NOT NULL,
 Title NVARCHAR(250) ,
 CreatedOn DATETIME NOT NULL DEFAULT GETDATE(),
 Impressions INT NOT NULL DEFAULT GETDATE(),
 IsDeleted BIT NOT NULL DEFAULT 0,
 IsPublished BIT NOT NULL DEFAULT 0,
 RowCreatedTimeStamp DATETIME NOT NULL DEFAULT GETDATE()
)

ALTER TABLE Article 
ADD CONSTRAINT FK_Article_Author FOREIGN KEY (AuthorId) REFERENCES Author(AuthorId)